import Link from 'next/link'

const sections = [
  { title: 'Definitions and key terms', content: 'Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.\n\nCompany: when this policy mentions "Company," "we," "us," or "our," it refers to Fidelio, that is responsible for your information under this Cookie Policy.\n\nDevice: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Fidelio and use the services.\n\nPersonal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.\n\nWebsite: Fidelio\'s site, which can be accessed via this URL: getfidelio.app' },
  { title: 'Introduction', content: 'This Cookie Policy explains how Fidelio and its affiliates (collectively "Fidelio", "we", "us", and "ours"), use cookies and similar technologies to recognize you when you visit our website, including without limitation getfidelio.app and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains what these technologies are and why we use them, as well as the choices for how to control them.' },
  { title: 'What is a cookie?', content: 'A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They\'re completely safe and can\'t be used to run programs or deliver viruses to your device.' },
  { title: 'Why do we use cookies?', content: 'We use first party and/or third party cookies on our website for various purposes such as:\n\n— To facilitate the operation and functionality of our website;\n— To improve your experience of our website and make navigating around them quicker and easier;\n— To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you;\n— To analyze how our website is used and how best we can customize it.' },
  { title: 'Essential Cookies', content: 'We use essential cookies to make our website work. These cookies are strictly necessary to enable core functionality such as security, network management, your cookie preferences and accessibility. Without them you wouldn\'t be able to use basic services. You may disable these by changing your browser settings, but this may affect how the Websites function.' },
  { title: 'Performance and Functionality Cookies', content: 'These cookies are used to enhance the performance and functionality of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website as we would not be able to remember that you had logged in previously.' },
  { title: 'Local Storage', content: 'Local Storage (sometimes known as DOM storage) provides web apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header. We use local storage to improve your experience on the Fidelio PWA.' },
  { title: 'Sessions', content: 'We use "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on your computer or mobile device by your web browser. Sessions expire when you close your browser.' },
  { title: 'Third Party Cookies', content: 'Some cookies that have been set on our website are not set on a first party basis by Fidelio. We use Clerk for authentication, which may set its own cookies to manage user sessions. These third party service providers control their own cookies and we do not control the use of these third party cookies.' },
  { title: 'How you can manage cookies?', content: 'Most browsers allow you to control cookies through their settings preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may also stop you from saving customized settings like login information.\n\nYou can manage cookies in: Google Chrome, Mozilla Firefox, Safari (Desktop), Safari (Mobile), Android Browser.' },
  { title: 'Blocking and disabling cookies and similar technologies', content: 'Wherever you\'re located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser.' },
  { title: 'Changes To Our Cookie Policy', content: 'We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you before we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect.' },
  { title: 'Your Consent', content: 'By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.' },
  { title: 'Contact Us', content: 'Don\'t hesitate to contact us if you have any questions regarding our Cookie Policy.\n\nEmail: support@getfidelio.app\nWebsite: getfidelio.app' },
]

export default function CookiePolicyPage() {
  return (
    <div style={{ fontFamily: 'system-ui,sans-serif', background: '#0D0D1A', color: 'white', minHeight: '100vh', padding: '2rem', maxWidth: '800px', margin: '0 auto' }}>
      <Link href="/" style={{ color: '#A78BFA', textDecoration: 'none', fontSize: '0.9rem' }}>← Torna alla home</Link>
      <h1 style={{ fontSize: '2rem', fontWeight: '800', margin: '2rem 0 0.5rem' }}>Cookie Policy</h1>
      <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.85rem', marginBottom: '2rem' }}>Updated at 2026-04-17</p>
      {sections.map(section => (
        <div key={section.title} style={{ marginBottom: '1.5rem' }}>
          <h2 style={{ fontSize: '1.1rem', fontWeight: '700', marginBottom: '0.5rem', color: '#A78BFA' }}>{section.title}</h2>
          {section.content.split('\n\n').map((para, i) => (
            <p key={i} style={{ color: 'rgba(255,255,255,0.6)', lineHeight: '1.7', fontSize: '0.9rem', marginBottom: '0.5rem' }}>{para}</p>
          ))}
        </div>
      ))}
    </div>
  )
}
